import type * as React from 'react';

export { AlertCircleIcon } from './alert-circle';
export { AlertTriangleIcon } from './alert-triangle';
export { ArrowLeftIcon } from './arrow-left';
export { BarChartIcon } from './bar-chart';
export { BoldIcon } from './bold';
export { BookIcon } from './book';
export { BriefcaseIcon } from './briefcase';
export { CheckCircleIcon } from './check-circle';
export { CheckSquareIcon } from './check-square';
export { CheckIcon } from './check';
export { ChevronDownIcon } from './chevron-down';
export { ChevronLeftIcon } from './chevron-left';
export { ChevronUpIcon } from './chevron-up';
export { CodeIcon } from './code';
export { CopyIcon } from './copy';
export { ExternalLinkIcon } from './external-link';
export { EyeIcon } from './eye';
export { FileIcon } from './file';
export { FolderIcon } from './folder';
export { GitMergeIcon } from './git-merge';
export { GlobeIcon } from './globe';
export { Heading2Icon } from './heading-2';
export { Heading3Icon } from './heading-3';
export { HomeIcon } from './home';
export { ImagePlusIcon } from './image-plus';
export { ImageIcon } from './image';
export { InfoIcon } from './info';
export { LaptopIcon } from './laptop';
export { ItalicIcon } from './italic';
export { LayoutIcon } from './layout';
export { LinkIcon } from './link';
export { ListOrderedIcon } from './list-ordered';
export { ListIcon } from './list';
export { LoaderIcon } from './loader';
export { LogOutIcon } from './log-out';
export { MailIcon } from './mail';
export { MessageCircleIcon } from './message-circle';
export { MinusIcon } from './minus';
export { MoonIcon } from './moon';
export { PlusIcon } from './plus';
export { PuzzleIcon } from './puzzle';
export { QuoteIcon } from './quote';
export { RedoIcon } from './redo';
export { RouteIcon } from './route';
export { SendIcon } from './send';
export { ServerIcon } from './server';
export { ShieldIcon } from './shield';
export { SparklesIcon } from './sparkles';
export { StrikethroughIcon } from './strikethrough';
export { SunIcon } from './sun';
export { TagIcon } from './tag';
export { TerminalIcon } from './terminal';
export { TrashIcon } from './trash';
export { TypeIcon } from './type';
export { UndoIcon } from './undo';
export { UserIcon } from './user';
export { WandIcon } from './wand';
export { XIcon } from './x';
export { ZapIcon } from './zap';

export type IconComponent = React.ComponentType<
  React.SVGProps<SVGSVGElement> & { size?: number | string }
>;
